// export const host = "https://server-dgj4adfq5q-ue.a.run.app";
export const host = "http://localhost:8080";
export const registerRoute = `${host}/api/auth/register`;
export const loginRoute = `${host}/api/auth/login`;
export const allUsersRoute = `${host}/api/auth/allUsers`;
export const sendMsgRoute = `${host}/api/messages/addmsg`;
export const getMsgsRoute = `${host}/api/messages/getmsg`;
export const getMoodRoute = `${host}/api/mood/getmoods`;
export const addMoodRoute = `${host}/api/mood/addmood`;